#include <hash_map>
#include "Credentials.h"



Credentials::Credentials(const std::string& username, const std::string& nonHashedPassword)
	:m_username(username)
{
	this->m_hashedPassword = hashString(nonHashedPassword);
}

/// <summary>
/// Hash a string
/// </summary>
/// <param name="stringToBeHashed">The string to be hashed</param>
/// <returns>An integer that is uniquely generated by the hasher</returns>
std::size_t hashString(const std::string& stringToBeHashed)
{
	std::hash<std::string> _hasher;

	return _hasher(stringToBeHashed);
}